const MEDS=['L-carnitine(100)','Vit C','Vit D2','Vit D3','Vit B12 500mcg','鐵劑(100)','A20(0.3)','A30(0.45)','A40','Amino-RF(235)','Albumin(1300)','smofkarbiven'];
const SYMPTOMS=['頭暈','冒汗','想吐','打哈欠','愛睏','眼睛模糊','腹痛','有便意','心悸'];
const TREATMENTS=['UF off','N/S','Midodrine','UF 下調'];
const CHECKS=['Permcath 已消毒','備藥完成','Lock 已抽好','收針物品已備妥'];
const KEY='hd-workflow-mvp-v1'; let beds=load(), notified=new Set();
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return []}} function save(){localStorage.setItem(KEY,JSON.stringify(beds))}
function todayAt(hm){const d=new Date();const [h,m]=hm.split(':').map(Number);d.setHours(h,m,0,0);return d} function hm(d){return d.toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false})}
function minsBetween(a,b){return Math.round((b-a)/60000)} function uid(){return crypto.randomUUID?.()||Date.now()+Math.random().toString(16).slice(2)}
function taskLabel(type){return type==='vs'?'生命徵象 VS':type==='iron'?'鐵劑提醒':type==='amino'?'Amino-RF 提醒':type==='albumin'?'Albumin 提醒':'結束前 10 分鐘'}
function tasksFor(b){if(b.ended)return[];const start=new Date(b.start),end=new Date(b.plannedEnd),out=[];for(let t=new Date(start.getTime()+3600000);t<end;t=new Date(t.getTime()+3600000))out.push({id:`${b.id}-vs-${t.getTime()}`,bed:b.name,type:'vs',time:t}); if(b.meds.includes('鐵劑(100)'))out.push({id:`${b.id}-iron`,bed:b.name,type:'iron',time:new Date(end-1800000)}); if(b.meds.includes('Amino-RF(235)'))out.push({id:`${b.id}-amino`,bed:b.name,type:'amino',time:new Date(end-3600000)});if(b.meds.includes('Albumin(1300)'))out.push({id:`${b.id}-albumin`,bed:b.name,type:'albumin',time:new Date(end-3600000)});out.push({id:`${b.id}-end10`,bed:b.name,type:'end',time:new Date(end-600000)});return out.sort((a,b)=>a.time-b.time)}
function allTasks(){return beds.flatMap(tasksFor).sort((a,b)=>a.time-b.time)}
function render(){const now=new Date(),tasks=allTasks(),upcoming=tasks.filter(t=>t.time>=new Date(now-30*60000));const next=upcoming[0];$('#nextHero').className='next-hero'+(next?'':' empty');$('#nextHero').innerHTML=next?`<div class="next-time">${hm(next.time)}</div><div><strong>${esc(next.bed)} · ${taskLabel(next.type)}</strong><div class="next-meta">${minsBetween(now,next.time)<=0?'已到時間':`${minsBetween(now,next.time)} 分鐘後`}</div></div>`:'目前沒有進行中的透析';$('#timeline').innerHTML=upcoming.slice(0,8).map(t=>`<div class="task ${t.time<now?'overdue':''}"><span class="task-time">${hm(t.time)}</span><span><b>${esc(t.bed)}</b> · ${taskLabel(t.type)}</span><span class="pill">${t.time<now?'已到時':minsBetween(now,t.time)+' min'}</span></div>`).join('');$('#bedCount').textContent=`${beds.filter(b=>!b.ended).length} 床進行中`;$('#beds').innerHTML=beds.length?beds.map(bedHTML).join(''):'<div class="empty-card">尚無床位，按「新增床位」開始。</div>'}
function bedHTML(b){const start=new Date(b.start),end=new Date(b.ended?b.actualEnd:b.plannedEnd),duration=Math.max(0,minsBetween(start,end)),tasks=tasksFor(b);return `<article class="bed-card ${b.ended?'ended':''}"><div class="bed-top"><div><h3>${esc(b.name)}</h3><div class="bed-time">${hm(start)} → ${hm(new Date(b.plannedEnd))}${b.ended?` · 實際 ${hm(end)}（${Math.floor(duration/60)} 小時 ${duration%60} 分）`:''}</div></div><span class="pill">${b.ended?'已結束':`進行中`}</span></div><div class="bed-body"><div><div class="mini-title">工作檢核</div><div class="check-list">${CHECKS.map((c,i)=>`<label class="check-row"><input type="checkbox" data-check="${b.id}" data-index="${i}" ${b.checks[i]?'checked':''}><span>${c}${b.checkTimes?.[i]?` <small>${b.checkTimes[i]}</small>`:''}</span></label>`).join('')}</div></div><div><div class="mini-title">此次藥物</div><div class="med-list">${b.meds.length?b.meds.map(m=>`<span class="med">${esc(m)}</span>`).join(''):'<span class="bed-time">未勾選</span>'}</div></div>${!b.ended?`<div><div class="mini-title">接續提醒</div>${tasks.slice(0,5).map(t=>`<div class="bed-time">${hm(t.time)}　${taskLabel(t.type)}</div>`).join('')}</div>`:''}<div><div class="mini-title">臨時紀錄（${b.records.length}）</div><div class="records">${b.records.slice(-4).reverse().map(recordHTML).join('')||'<span class="bed-time">尚無紀錄</span>'}</div></div><div class="bed-actions">${!b.ended?`<button class="small" data-record="vs" data-id="${b.id}">＋ 生命徵象</button><button class="small secondary" data-record="event" data-id="${b.id}">＋ 不適事件</button><button class="small danger" data-end="${b.id}">提前結束</button>`:''}<button class="small secondary" data-delete="${b.id}">刪除</button></div></div></article>`}
function recordHTML(r){const vitals=[r.temp&&`T ${r.temp}℃`,r.pulse&&`P ${r.pulse}`,r.resp&&`R ${r.resp}`,r.sbp&&r.dbp&&`BP ${r.sbp}/${r.dbp}`].filter(Boolean).join(' · '),details=[...r.symptoms,r.otherSymptom,...r.treatments,r.otherTreatment,r.notes].filter(Boolean).join('；');return `<div class="record"><b>${esc(r.time)} · ${r.type==='event'?'不適事件':'生命徵象'}</b><br>${esc(vitals||'未填生命徵象')}${details?`<br>${esc(details)}`:''}</div>`}
function options(el,items,name){el.innerHTML=items.map(x=>`<label><input type="checkbox" name="${name}" value="${esc(x)}">${esc(x)}</label>`).join('')}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),5000);try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=880;g.gain.value=.13;o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.35)}catch{}}
function checkAlerts(){const now=Date.now();allTasks().forEach(t=>{if(Math.abs(t.time-now)<30000&&!notified.has(t.id)){notified.add(t.id);const msg=`${t.bed}：${taskLabel(t.type)}`;toast(msg);if(Notification.permission==='granted')new Notification('透析工作提醒',{body:msg})}})}
options($('#medOptions'),MEDS,'med');options($('#symptomOptions'),SYMPTOMS,'symptom');options($('#treatmentOptions'),TREATMENTS,'treatment');
$('#addBedBtn').onclick=()=>{const now=new Date();$('#startTime').value=hm(now);$('#bedDialog').showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#bedForm').onsubmit=e=>{e.preventDefault();const start=todayAt($('#startTime').value),duration=Number($('#duration').value),end=new Date(start.getTime()+duration*3600000);beds.unshift({id:uid(),name:$('#bedName').value.trim(),start:start.toISOString(),plannedEnd:end.toISOString(),meds:[...document.querySelectorAll('[name=med]:checked')].map(x=>x.value),checks:[false,false,false,false],checkTimes:[null,null,null,null],records:[],ended:false});save();e.target.reset();$('#duration').value=4;$('#bedDialog').close();render()};
$('#beds').onclick=e=>{const check=e.target.closest('[data-check]');if(check){const b=beds.find(x=>x.id===check.dataset.check),i=+check.dataset.index;b.checks[i]=check.checked;b.checkTimes[i]=check.checked?hm(new Date()):null;save();render();return}const rec=e.target.closest('[data-record]');if(rec){const b=beds.find(x=>x.id===rec.dataset.id);$('#recordBedId').value=b.id;$('#recordType').value=rec.dataset.record;$('#recordBed').textContent=b.name;$('#recordTitle').textContent=rec.dataset.record==='event'?'新增不適事件':'新增生命徵象';$('#recordTime').value=hm(new Date());$('#treatmentField').hidden=rec.dataset.record!=='event';$('#recordDialog').showModal();return}const end=e.target.closest('[data-end]');if(end){$('#endBedId').value=end.dataset.end;$('#actualEnd').value=hm(new Date());$('#endDialog').showModal();return}const del=e.target.closest('[data-delete]');if(del&&confirm('確定刪除此床位與所有紀錄？')){beds=beds.filter(x=>x.id!==del.dataset.delete);save();render()}};
$('#recordForm').onsubmit=e=>{e.preventDefault();const b=beds.find(x=>x.id===$('#recordBedId').value);b.records.push({id:uid(),type:$('#recordType').value,time:$('#recordTime').value,temp:$('#temp').value,pulse:$('#pulse').value,resp:$('#resp').value,sbp:$('#sbp').value,dbp:$('#dbp').value,symptoms:[...document.querySelectorAll('[name=symptom]:checked')].map(x=>x.value),otherSymptom:$('#otherSymptom').value.trim(),treatments:[...document.querySelectorAll('[name=treatment]:checked')].map(x=>x.value),otherTreatment:$('#otherTreatment').value.trim(),notes:$('#notes').value.trim()});save();e.target.reset();$('#recordDialog').close();render()};
$('#endForm').onsubmit=e=>{e.preventDefault();const b=beds.find(x=>x.id===$('#endBedId').value),actual=todayAt($('#actualEnd').value);b.ended=true;b.actualEnd=actual.toISOString();save();$('#endDialog').close();render();toast(`${b.name} 已結束，後續提醒已取消`)};
$('#notifyBtn').onclick=async()=>{toast('提示音已啟用');if('Notification'in window){const p=await Notification.requestPermission();$('#notifyBtn').textContent=p==='granted'?'🔔 提醒已啟用':'🔕 僅頁面提醒'}};
setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString('zh-TW',{hour12:false});checkAlerts();render()},1000);render();
